//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Payments struct {
	ID              string `sql:"primary_key"`
	PaymentMethodID string
	Amount          int64
	Status          string
	ExpiryTime      time.Time
	CallbackURL     string
	RedirectURL     string
	MerchantID      string
	MerchantOrderID string
	CustomerEmail   string
	CustomerName    string
	CustomerPhone   string
	ProductDetails  string
	CreatedAt       time.Time
}
