//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Payments struct {
	ID              string `sql:"primary_key"`
	PaymentMethodID string
	Amount          int64
	Description     string
	Status          string
	CallbackURL     string
	MerchantID      string
	MerchantOrderID string
	UserEmail       string
	UserName        string
	CreatedAt       time.Time
}
