//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Payments = newPaymentsTable("public", "payments", "")

type paymentsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	PaymentMethodID postgres.ColumnString
	Amount          postgres.ColumnInteger
	Description     postgres.ColumnString
	Status          postgres.ColumnString
	CallbackURL     postgres.ColumnString
	RedirectURL     postgres.ColumnString
	MerchantID      postgres.ColumnString
	MerchantOrderID postgres.ColumnString
	UserEmail       postgres.ColumnString
	UserName        postgres.ColumnString
	CreatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PaymentsTable struct {
	paymentsTable

	EXCLUDED paymentsTable
}

// AS creates new PaymentsTable with assigned alias
func (a PaymentsTable) AS(alias string) *PaymentsTable {
	return newPaymentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PaymentsTable with assigned schema name
func (a PaymentsTable) FromSchema(schemaName string) *PaymentsTable {
	return newPaymentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PaymentsTable with assigned table prefix
func (a PaymentsTable) WithPrefix(prefix string) *PaymentsTable {
	return newPaymentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PaymentsTable with assigned table suffix
func (a PaymentsTable) WithSuffix(suffix string) *PaymentsTable {
	return newPaymentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPaymentsTable(schemaName, tableName, alias string) *PaymentsTable {
	return &PaymentsTable{
		paymentsTable: newPaymentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newPaymentsTableImpl("", "excluded", ""),
	}
}

func newPaymentsTableImpl(schemaName, tableName, alias string) paymentsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		PaymentMethodIDColumn = postgres.StringColumn("payment_method_id")
		AmountColumn          = postgres.IntegerColumn("amount")
		DescriptionColumn     = postgres.StringColumn("description")
		StatusColumn          = postgres.StringColumn("status")
		CallbackURLColumn     = postgres.StringColumn("callback_url")
		RedirectURLColumn     = postgres.StringColumn("redirect_url")
		MerchantIDColumn      = postgres.StringColumn("merchant_id")
		MerchantOrderIDColumn = postgres.StringColumn("merchant_order_id")
		UserEmailColumn       = postgres.StringColumn("user_email")
		UserNameColumn        = postgres.StringColumn("user_name")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		allColumns            = postgres.ColumnList{IDColumn, PaymentMethodIDColumn, AmountColumn, DescriptionColumn, StatusColumn, CallbackURLColumn, RedirectURLColumn, MerchantIDColumn, MerchantOrderIDColumn, UserEmailColumn, UserNameColumn, CreatedAtColumn}
		mutableColumns        = postgres.ColumnList{PaymentMethodIDColumn, AmountColumn, DescriptionColumn, StatusColumn, CallbackURLColumn, RedirectURLColumn, MerchantIDColumn, MerchantOrderIDColumn, UserEmailColumn, UserNameColumn, CreatedAtColumn}
		defaultColumns        = postgres.ColumnList{CreatedAtColumn}
	)

	return paymentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		PaymentMethodID: PaymentMethodIDColumn,
		Amount:          AmountColumn,
		Description:     DescriptionColumn,
		Status:          StatusColumn,
		CallbackURL:     CallbackURLColumn,
		RedirectURL:     RedirectURLColumn,
		MerchantID:      MerchantIDColumn,
		MerchantOrderID: MerchantOrderIDColumn,
		UserEmail:       UserEmailColumn,
		UserName:        UserNameColumn,
		CreatedAt:       CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
