//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PaymentMethods = newPaymentMethodsTable("public", "payment_methods", "")

type paymentMethodsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	Name          postgres.ColumnString
	BigImageURL   postgres.ColumnString
	SmallImageURL postgres.ColumnString
	TotalFee      postgres.ColumnInteger
	Category      postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PaymentMethodsTable struct {
	paymentMethodsTable

	EXCLUDED paymentMethodsTable
}

// AS creates new PaymentMethodsTable with assigned alias
func (a PaymentMethodsTable) AS(alias string) *PaymentMethodsTable {
	return newPaymentMethodsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PaymentMethodsTable with assigned schema name
func (a PaymentMethodsTable) FromSchema(schemaName string) *PaymentMethodsTable {
	return newPaymentMethodsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PaymentMethodsTable with assigned table prefix
func (a PaymentMethodsTable) WithPrefix(prefix string) *PaymentMethodsTable {
	return newPaymentMethodsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PaymentMethodsTable with assigned table suffix
func (a PaymentMethodsTable) WithSuffix(suffix string) *PaymentMethodsTable {
	return newPaymentMethodsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPaymentMethodsTable(schemaName, tableName, alias string) *PaymentMethodsTable {
	return &PaymentMethodsTable{
		paymentMethodsTable: newPaymentMethodsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newPaymentMethodsTableImpl("", "excluded", ""),
	}
}

func newPaymentMethodsTableImpl(schemaName, tableName, alias string) paymentMethodsTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		NameColumn          = postgres.StringColumn("name")
		BigImageURLColumn   = postgres.StringColumn("big_image_url")
		SmallImageURLColumn = postgres.StringColumn("small_image_url")
		TotalFeeColumn      = postgres.IntegerColumn("total_fee")
		CategoryColumn      = postgres.StringColumn("category")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		allColumns          = postgres.ColumnList{IDColumn, NameColumn, BigImageURLColumn, SmallImageURLColumn, TotalFeeColumn, CategoryColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{NameColumn, BigImageURLColumn, SmallImageURLColumn, TotalFeeColumn, CategoryColumn, CreatedAtColumn}
		defaultColumns      = postgres.ColumnList{CreatedAtColumn}
	)

	return paymentMethodsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		Name:          NameColumn,
		BigImageURL:   BigImageURLColumn,
		SmallImageURL: SmallImageURLColumn,
		TotalFee:      TotalFeeColumn,
		Category:      CategoryColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
