//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PaymentMethods struct {
	ID            string `sql:"primary_key"`
	Name          string
	BigImageURL   string
	SmallImageURL string
	TotalFee      int32
	Category      string
	CreatedAt     time.Time
}
